cmCustomer/cmCustomer/Controllers/mcCustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cmCustomer.Models;

namespace cmCustomer.Controllers
{
    public class mcCustomersController : Controller
    {
        private DataContext db = new DataContext();

        // GET: mcCustomers
        public ActionResult Index(String name)
        {
            return View(db.mcCustomers.Where(x => x.CustomerName.StartsWith(name)|| name ==null).ToList());
        }

        // GET: mcCustomers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mcCustomer mcCustomer = db.mcCustomers.Find(id);
            if (mcCustomer == null)
            {
                return HttpNotFound();
            }
            return View(mcCustomer);
        }

        // GET: mcCustomers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: mcCustomers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,CustomerName,CustomerAddress,Remarks")] mcCustomer mcCustomer)
        {
            if (ModelState.IsValid)
            {
                db.mcCustomers.Add(mcCustomer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mcCustomer);
        }

        // GET: mcCustomers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mcCustomer mcCustomer = db.mcCustomers.Find(id);
            if (mcCustomer == null)
            {
                return HttpNotFound();
            }
            return View(mcCustomer);
        }

        // POST: mcCustomers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,CustomerName,CustomerAddress,Remarks")] mcCustomer mcCustomer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mcCustomer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mcCustomer);
        }

        // GET: mcCustomers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mcCustomer mcCustomer = db.mcCustomers.Find(id);
            if (mcCustomer == null)
            {
                return HttpNotFound();
            }
            return View(mcCustomer);
        }

        // POST: mcCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            mcCustomer mcCustomer = db.mcCustomers.Find(id);
            db.mcCustomers.Remove(mcCustomer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cmCustomer/cmCustomer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        @Html.ActionLink("mcCustomer Web App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Customer", "Index", "mcCustomers", new { area = "" }, new { @class = "nav-link" })
                </li>

            </ul>
                    @Html.Partial("_LoginPartial")
        </div>
    </nav>
</header>
<main class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - mcCustomer Application</p>
    </footer>
</main>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>